//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommndesNaza.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Taxe = 0.18D;
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string MoreInformations { get; set; }
        public double Taxe { get; set; }
        public double SubTotal { get; set; }
        public double Total { get; set; }
        public string Statut { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Client Client { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Ivoice Ivoice { get; set; }
        public virtual Payment Payment { get; set; }

        public override string ToString()
        {
            return $"{Client} : Ref order {Reference}";
        }
    }
}
