//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommndesNaza.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Reference { get; set; }
        public double Amount { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> PaidAt { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
